@startuml
package testapp {
    class ExampleTestModel {
        {field} -char_field : CharField(max_length=30)
    }
}
package other_test_app {
    class OtherModel {
        {field} -char_field : CharField(max_length=30)
    }
}
@enduml