@startuml
left to right direction
package people {
    abstract class AbstractPerson {
        {field} -first_name : CharField(max_length=255)
        {field} -last_name : CharField(max_length=255)
        {field} birth_date : DateField()
        {field} mother_name : CharField()
        {field} father_name : CharField()
    }

    class Student {
        {field} ufrrj_id : CharField()
    }
    AbstractPerson <- Student : inherit

    class Instructor {
        {field} ufrrj_id : PositiveIntegerField()
    }
    AbstractPerson <- Instructor : inherit
}
package educational {
    class SchoolarPeriod {
        {field} name : CharField(max_length=255)
        {field} start_date : DateField()
        {field} end_date : DateField()
    }
    class Subject {
        use_slug(name)
        rest_api_writable_nested_objects(SubjectLevel,SubjectRequirement)
        {field} #title : CharField(max_length=255)
        {field} #name : CharField(max_length=255)
    }
    class SubjectLevel {
        {field} subject : ForeignKey('Subject')
        {field} title : CharField(max_length=255)
        {field} description : TextField()
        unique_together(subject,title)
    }
    class SubjectRequirement {
        {field} subject : ForeignKey('Subject')
        {field} title : CharField(max_length=255)
        {field} description : TextField()
    }
    class SubjectClass {
        {field} subject : ForeignKey('Subject')
        {field} subject_level : ForeignKey('SubjectLevel')
        {field} title : CharField(max_length=255)
        {field} capacity : IntegerField()
        {field} start_date : DateField()
        {field} end_date : DateField()
    }
    class SubjectClassSchedulePeriod {
        {field} subject_class : ForeignKey('SubjectClass')
        {field} day_of_week : CharField(max_length=255)
        {field} from_hour : TimeField()
        {field} to_time : TimeField()
        unique_together(subject_class,day_of_week,from_hour,to_time) 
    }
}
package infrastructure {
    class Building{
        use_slug(name)
        rest_api_writable_nested_objects(WorkingPeriod)
        {field} #name : CharField(max_length=255)
    }
    class ClassRoom {
        use_slug(name)
        rest_api_writable_nested_objects(WorkingPeriod)
        {field} building : ForeignKey('Building')
        {field} name : CharField(max_length=255)
        unique_together(building,name) 
    }
    class WorkingPeriod  {
        {field} building : ForeignKey('Building')
        {field} class_room : ForeignKey('ClassRoom')
        {field} day_of_week : CharField(max_length=255)
        {field} from_hour : TimeField()
        {field} to_time : TimeField()
    }
}
@enduml