GENERATE_FIELDS_HELP_TEXT = True

OUTPUT_PATH = "uml2django_output"

CHAR_FIELD_SHORTCUT = "CF"
CHAR_FIELD_MAX_LENGTH = 255

DECIMAL_FIELD_SHORTCUT = "DF"
DECIMAL_FIELD_DECIMAL_PLACES = 4
DECIMAL_FIELD_MAX_DIGITS = 11
