class settings:
    GENERATE_FIELDS_HELP_TEXT = True

    OUTPUT_PATH = "uml2django_output"

    CHAR_FIELD_SHORTCUT = "CF"
    CHAR_FIELD_MAX_LENGTH = 255

    DECIMAL_FIELD_SHORTCUT = "DF"
    DECIMAL_FIELD_DECIMAL_PLACES = 4
    DECIMAL_FIELD_MAX_DIGITS = 11

    UML2DJANGO_USE_DJANGO_CRISPY_FORMS = True
    UML2DJANGO_USE_BASE_TEMPLATE = True
    UML2DJANGO_BASE_TEMPLATE = "base.html"
    UML2DJANGO_BASE_TEMPLATE_CONTENT_BLOCK_NAME = "base_content"
    UML2DJANGO_USE_I18N = True
