"""
    Tag names of XMI file 
    generated by PlantUml 
    using ArgoUml syntax
"""

XMI_ARGO_CLASS_TAG_NAME = "UML:Class"
XMI_ARGO_ROOT_NAMESPACE_TAG_NAME = "UML:Namespace.ownedElement"
XMI_ARGO_ASSOCIATION_TAG_NAME = "UML:Association"